### ISSUE TITLE
Resource metrics

### ISSUE THREAD

**Issue by electrical** [atomix/atomix#100]
Not sure if it belongs here but it would be nice to add some resource statistics that can be pulled.
For example number of entries in a DistributedValue or DistributedTaskQueue.
Unsure what kind of metadata is already being stored?

**Comment by jhalterman** [comment]
TaskQueue and MembershipGroup could certainly get a `size` method. DistributedLock could potentially provide info about the waiting processes and the queue length, similar to ReentrantLock.

**Comment by madjam** [comment]
Speaking of statistics, the number of times each resource operation is invoked might be useful to track and expose. Other statistics (like the task queue `size`) are resource specific can be made visible via appropriate resource operations.

Coming to other statistics in the system: 
* It would be useful to exposes some session specific metrics. Such as total number of active sessions, their establishment times, total operations submitted/succeeded/failed per session.
* There may be metrics that can captured/exposed for the `Log` subsystem and how compaction tasks are progressing.
* There could be a whole host of latency/exception metrics that would be useful to capture to provide some visibility into the running system.

**Comment by kuujo** [comment]
Ahh I love those ideas @madjam... Thinking big!

These are the types of things that just need to mature over time.
Definitely todo tasks for after the 1.0 release :-)

**Comment by jhalterman** [comment]
@madjam I've thought about some of those things too. Being able to peak into the internals, particularly on the server side, would be very valuable. Atomix and Copycat are, so far, relatively lightweight with minimal dependencies. So then I'm wondering, do you roll your own metrics API or do you integrate something like https://github.com/dropwizard/metrics which is very nice and already exists. I'd opt to integrate metrics, but then you have this added overhead of metrics for people who might not necessarily care for them.

**Comment by electrical** [comment]
I think using an existing system makes complete sense. I see to many people building their own things ( none invented here )
Potentially it could be made optional? Have metrics gathering a flag you can set.
The code will still be there but won't be executed unless activated.

Would be nice if people could build their own 'drivers' to export the data to some system.

**Comment by electrical** [comment]
dropwizard/metrics has a nice system to implement different drivers so that would be nice to use.
I assume metrics for active resources are processed by the active master at that time?
And then you also have separate metrics per 'node'.

I can imagine this collecting process runs on a separate thread to not mess up other threads?

**Comment by jhalterman** [comment]
@electrical The various metrics are threadsafe, so collection/recording happens in whatever thread something is happening in - like the thread that happens to be placing something in a task queue. Reporting can be done in a number of ways, such as via web server, that that stuff could run in separate threads.

**Comment by electrical** [comment]
I guess we could make a light abstraction over `dropwizard/metrics` but we will still need to add the calls to all the different resources.
Might need some help with that part :-)

**Comment by electrical** [comment]
before building anything i think its useful to describe what kind of metrics we would like to implement per resource?
As an example: 


* DistributedMap
  * Count of resources
  * Per resource:
    * Count of items ( size )
    * Total function calls
    * Count of each function calls ( isEmpty, size, containsKey, containsValue, get, getOrDefault, put, putIfAbsent, remove, replace, keySet, clear )

**Comment by jhalterman** [comment]
For the collection resources I'd like to see the size. For MessageBus, Topic and TaskQueue maybe have consumer timers. For DistributedGroup, leader election and remote execution timers. Since we're returning `CompletableFuture` for a lot of operations, it might be useful to create an instrumented CompletableFuture that can time operations. ([Here's](https://github.com/openstack/monasca-common/blob/master/java/monasca-common-util/src/main/java/monasca/common/util/concurrent/InstrumentedThreadPoolExecutor.java) an instrumented ThreadPoolExecutor that gives you an idea how this sort of thing can be done).

I'm most interested to see metrics for internal things though - leader election, operation latency, stuff like that.

**Comment by jhalterman** [comment]
Also useful - the number of tombstones in a log.
