### ISSUE TITLE
RaftServer.Builder#withStateMachine Cannot find

### ISSUE THREAD

**Issue by mingfer** [atomix/atomix#1001]
The following code snippet is mentioned in the comments of the RaftServer interface. The `withStateMachine(MyStateMachine::new)` method  in the code is not defined in the interface. 

```java
 RaftServer server = RaftServer.builder(address)
   .withStateMachine(MyStateMachine::new)
   .withStorage(Storage.builder()
     .withDirectory(new File("logs"))
     .withStorageLevel(StorageLevel.DISK)
     .build())
   .build();
```
Is the method expired or has been deleted, is there an alternative method?

**Comment by Samhom** [comment]
The builder(...) method can only accept the MemberId parameter instead of Address, but the buider(address) method is also an example provided in the RaftServer interface annotation.
