### ISSUE TITLE
Page not found when access user manual at atomix.io site

### ISSUE THREAD

**Issue by kitepad** [atomix/atomix#1019]
**Expected behavior**
Installation and Setup page is loaded

**Actual behavior**

Page not found

**Steps to reproduce**

Steps to reproduce the behavior.

**Minimal yet complete reproducer code (or URL to code)**

```java

```

**Environment**

 - Atomix: [e.g. 3.0.0]
 - OS: [e.g. `uname -a`]
 - JVM [e.g. `java -version`]

<sup>:warning:️ Please verify that your issue still occurs on the latest version of Atomix before reporting. 
The documentation is currently work-in-progress and is not yet complete.</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking in with the [Atomix Google Group](https://groups.google.com/forum/#!forum/atomixio)?*

**Comment by jhall11** [comment]
It seems to work fine for me, can you post the url for the broken link?

**Comment by kitepad** [comment]
For example, when I go to "User Manual" - https://atomix.io/docs/latest/user-manual/, then I click "Cluster Configuration", browser will open this url : https://atomix.io/docs/latest/user-manual/cluster-configuration.
"Page not found" will show. I have test some browser: chrome, firefox, ie, edge, all are same problem, BUT if I use some proxy server to load this site, all links are ok.

**Comment by kitepad** [comment]
And I think correct url should be https://atomix.io/docs/latest/user-manual/cluster-management/cluster-configuration/. I don't know why URL is not correct.

**Comment by johnou** [comment]
Cannot reproduce.
