### ISSUE TITLE
Remove apache commons* and guva

### ISSUE THREAD

**Issue by kitepad** [atomix/atomix#1020]
**Is your feature request related to a problem? Please describe.**

From my view, two depenencies have 4M+ size, I need more smaller size of atomix. 

**Describe the solution you'd like**

I have some investigate for source code, actually only a few functions are provided by them, most of functions are simply wrapper for jdk.

**Describe alternatives you've considered**

**Additional context**

**Comment by johnou** [comment]
@kitepad +1... Want to submit a PR? We love contributions :+1:
