### ISSUE TITLE
Atomix and Onos are eating a lot of memory

### ISSUE THREAD

**Issue by sndaergg** [atomix/atomix#1021]
I started three atomix instances and one Onos instance，**all of them are eating a lot of memory**, This should be abnormal ！！！

  PID USER             PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
23513 myname     20   0 14.179g 4.144g  18632 S   4.0 13.2 658:55.20 java
23615 myname     20   0 14.176g 4.413g  18472 S   3.3 14.0 528:34.98 java
23733 myname     20   0 14.174g 3.920g  18712 S   3.3 12.5 436:29.60 java
23913 myname     20   0 11.587g 2.593g  25588 S   3.3  8.3   1287:24 java

ps axu：
myname    23513  4.1 13.1 14868264 4345792 ?    Sl   Apr26 658:57 java -XX:+UseConcMarkSweepGC -Datomix.root=. -Datomix.data=./data -Datomix.logback=./conf/logback.xml -Datomix.log.directory=./log -Datomix.config.resources=./conf/atomix -Dvertx.disableFileCPResolving=true -cp .:./lib/system/*:./lib/ext/* io.atomix.agent.AtomixAgent -m uranus-atomix-1 -a 127.0.0.1:5901 --data-dir storage/data1 --http-port 5801

myname 23615  3.3 14.0 14864160 4627696 ?    Sl   Apr26 528:38 java -XX:+UseConcMarkSweepGC -Datomix.root=. -Datomix.data=./data -Datomix.logback=./conf/logback.xml -Datomix.log.directory=./log -Datomix.config.resources=./conf/atomix -Dvertx.disableFileCPResolving=true -cp .:./lib/system/*:./lib/ext/* io.atomix.agent.AtomixAgent -m uranus-atomix-2 -a 127.0.0.1:5902 --data-dir storage/data2 --http-port 5802
myname 23733  2.7 12.4 14862104 4110776 ?    Sl   Apr26 436:32 java -XX:+UseConcMarkSweepGC -Datomix.root=. -Datomix.data=./data -Datomix.logback=./conf/logback.xml -Datomix.log.directory=./log -Datomix.config.resources=./conf/atomix -Dvertx.disableFileCPResolving=true -cp .:./lib/system/*:./lib/ext/* io.atomix.agent.AtomixAgent -m uranus-atomix-3 -a 127.0.0.1:5903 --data-dir storage/data3 --http-port 5803

aiwan    23913  8.2  8.2 12149444 2718836 ?    Sl   Apr26 1287:29 /usr/bin/java -Xms2G -Xmx4G -Xloggc:data/log/gc.log.20190426162012 -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+HeapDumpOnOutOfMemoryError -Duser.timezone=GMT+8 -Djava.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/jre/lib/endorsed:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed:/opt/aiwan/uranus/apache-karaf-3.0.8/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/jre/lib/ext:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/opt/aiwan/uranus/apache-karaf-3.0.8/lib/ext -Dkaraf.instances=/opt/aiwan/uranus/apache-karaf-3.0.8/instances -Dkaraf.home=/opt/aiwan/uranus/apache-karaf-3.0.8 -Dkaraf.base=/opt/aiwan/uranus/apache-karaf-3.0.8 -Dkaraf.data=/opt/aiwan/uranus/apache-karaf-3.0.8/data -Dkaraf.etc=/opt/aiwan/uranus/apache-karaf-3.0.8/etc -Djava.io.tmpdir=/opt/aiwan/uranus/apache-karaf-3.0.8/data/tmp -Djava.util.logging.config.file=/opt/aiwan/uranus/apache-karaf-3.0.8/etc/java.util.logging.properties -Dkaraf.startLocalConsole=false -Dkaraf.startRemoteShell=true -classpath /opt/aiwan/uranus/apache-karaf-3.0.8/lib/karaf-jaas-boot.jar:/opt/aiwan/uranus/apache-karaf-3.0.8/lib/karaf-org.osgi.core.jar:/opt/aiwan/uranus/apache-karaf-3.0.8/lib/karaf.jar org.apache.karaf.main.Main

other infomation:
Onos version: 1.14.1
atomix version 3.0.7
atomix config:
cluster {
  cluster-id: uranus-atomix-cluster
  discovery {
    type: bootstrap
    nodes.1 {
      id: uranus-atomix-1
      address: "127.0.0.1:5901"
    }
    nodes.2 {
      id: uranus-atomix-2
      address: "127.0.0.1:5902"
    }
    nodes.3 {
      id: uranus-atomix-3
      address: "127.0.0.1:5903"
    }
  }
}

management-group {
  type: raft
  partitions: 1
  storage.level: disk
  members: [uranus-atomix-1, uranus-atomix-2, uranus-atomix-3]
}

partition-groups.raft {
  type: raft
  partitions: 3
  storage.level: disk
  members: [uranus-atomix-1, uranus-atomix-2, uranus-atomix-3]
}

**Comment by johnou** [comment]
without a reproducer or heap dump this is pretty much impossible to debug.
