### ISSUE TITLE
High Network usage and CPU consumption on Raft partitions without load and latency ~70 ms between nodes

### ISSUE THREAD

**Issue by kbujanecki** [atomix/atomix#1033]
**Expected behavior**

Minor network and CPU impact on cluster without load and 70 ms  latency between nodes

**Actual behavior**

Cluster sends 1 mbit/s data when latency is about ~70 ms.
Every 4-8ms leader node sends heartbeat 

**Steps to reproduce**

Setup 4 node cluster and simulate high latency with ie http://jagt.github.io/clumsy/

**Environment**

 - Atomix: 3.1.5

<sup>:warning:️ Please verify that your issue still occurs on the latest version of Atomix before reporting. 
The documentation is currently work-in-progress and is not yet complete.</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking in with the [Atomix Google Group](https://groups.google.com/forum/#!forum/atomixio)?*

**Comment by kuujo** [comment]
We have latency injection tests we can use to derisive with tc. The leader is sending heartbeats every 4-8ms, but what is its configuration? Can you share some TRACE logs from a leader for one of the partitions when this is happening? A few seconds should show _why_ it’s doing that.

**Comment by kbujanecki** [comment]
logs from cluster:
[atomix-issue.zip](https://github.com/atomix/atomix/files/3406723/atomix-issue.zip)

partitions configuration
managementGroup {
  type: raft
  partitions: 1
  storage.level: mapped
  storage.directory: atomix-data/system
  members: [node1, node2, node3, node4]
}

partitionGroups.raft {
  type: raft
  partitions: 7
  partitionSize: 3
  storage.level: mapped
  storage.directory: atomix-data/raft
  members: [node1, node2, node3, node4]
}

**Comment by johnou** [comment]
Please try again with the latest version and attach updated logs, there have been fixes to SWIM.
