### ISSUE TITLE
too much memory usage

### ISSUE THREAD

**Issue by peterkong752** [atomix/atomix#1050]
we have a 3 nodes raft servers, recently we found the memroy size is growing very fast, atomix logs said, "There is insufficient memory for the Java Runtime Environment to continue."

when we use the free -m command to view the memory, we found during the atomix-agent started from 2019-08-09 18:00 to 2019-08-11, in 48 hours, the used memory increased to 12GB, and after i killed the atomix-agent, this usage will be down to only about 450MB.

this issue happened before and we already upgraded atomix to version 3.0.15.
here is some information about our servers:
Java: openjdk version "1.8.0_131"
Atomix: 3.0.15
OS: Red Hat 4.8.5-16

could you please check this and let us know if there is some way to control this?

**Comment by sndaergg** [comment]
atomix version 3.0.15？

**Comment by peterkong752** [comment]
sorry, atomix version should be 3.1.0, 3.0.15 is a typo.

**Comment by skyfirst93** [comment]
We are using https://hub.docker.com/r/atomix/atomix for our deployment of atomix with ONOS. 
The version we are using is 3.0.7. The memory usage is too high with that version. So, Can we use 3.1.0 with Onos and does that solve the high memory usage issue

**Comment by johnou** [comment]
If you are still experiencing problems with the latest version please reopen with heap dumps.

**Comment by aggarwal-ankur-238** [comment]
@peterkong752 I am facing the same issue on the latest version 3.1.8 and was wondering if you were able to solve your issue? If so, could you let me know the solution

**Comment by peterkong752** [comment]
> @peterkong752 I am facing the same issue on the latest version 3.1.8 and was wondering if you were able to solve your issue? If so, could you let me know the solution

yes, because we found many logs about netty, but it is not fetal, we disabled this logging from logback.xml, also we modified the JVM size from 2GB to 4GB, and change down the maxEntrySize from 2MB to 64KB in atomix.conf, this issue went away.
