### ISSUE TITLE
What's the roadmap?

### ISSUE THREAD

**Issue by ajianzheng** [atomix/atomix#1056]
Branch 2.0 is updated iteratively recently,  and I'm confused about why is branch of 2.0? What are the responsibilities of the branch 2.0/3.0/4.0? What's the plan about those branches? 
I'am very interested in this project, and I'am sorry for this issue, but i have no way to ask question.
Thank you for your reading, and wait for your reply.

**Comment by damianoneill** [comment]
Are there any plans to support GraalVM?  Perhaps by offering Atomix on Quarkus?
