### ISSUE TITLE
question - when are you planning to release a new version? (latest 3.1.5)

### ISSUE THREAD

**Issue by mirkoAlic** [atomix/atomix#1059]
I been looking at the commits that are already merged in master and i noticed that there is a fix for a memory leak related to [Raft member selectors](https://github.com/atomix/atomix/commit/be6355f6c57586dc02109513f1cc58b8f4cf4213),  plus other improvements..
So i wondering if you are planning to release a new version soon? Btw, it would be really nice to have, because using the library we are experience those issues.

**Comment by johnou** [comment]
3.1.8 is in Maven central.
