### ISSUE TITLE
Architecture ARMv7

### ISSUE THREAD

**Issue by tiagozacarias** [atomix/atomix#1061]
Good afternoon people,

Is it possible to run this software on ARMv7 architecture?

In short it works on ARMv7 architecture?

I am integrating with ONOS for cluster management and had some problems integrating with docker. I've heard rumors that he doesn't run over ARM

**Comment by johnou** [comment]
For ONOS, please try the Google Group https://groups.google.com/a/onosproject.org/forum/#!forum/onos-dev
