### ISSUE TITLE
(Blocking)AtomicLock should notifies for state changes.

### ISSUE THREAD

**Issue by franz1981** [atomix/atomix#1071]
**Expected behavior**

BlockingAtomicLock should notifies for state changes.

**Actual behavior**

BlockingAtomicLock isn't implementing DistributedPrimitive::addStateChangeListener and removeStateChangeListener, hence won't be able to add/remove (and, by consequence, notify) listeners.

**Environment**

 - Atomix: 3.1.7

**Comment by johnou** [comment]
@franz1981 can you provide a pull request with unit test?

**Comment by franz1981** [comment]
Sure, will do it tomorrow :)
