### ISSUE TITLE
Workaround comment exists in pom.xml file while the related issues are already fixed.

### ISSUE THREAD

**Issue by markxiaotao** [atomix/atomix#1078]
**Expected behavior**

This workaround and comment should be removed or fixed

**Actual behavior**

In a research project, we analyzed the build file of repositories looking for comments with ready-to-be-addressed SATDs (self-admitted technical debt) that could be addressed. If the underlying issue is already resolved, the related code or comment can be removed or fixed. As we found an instance of this kind of asynchrony in pom.xml, we decided to report the issue to contribute community.
A comment in pom.xml file claims that it is workaround for https://bugs.openjdk.java.net/browse/JDK-8212233 and this issue has been RESOLVED long ago.

Comment location: 
https://github.com/atomix/atomix/blob/842276c02541267a61bca47f82c2e9d740245fcb/pom.xml#L358

**Comment by johnou** [comment]
I wouldn't consider this type of work around as technical dept.
