### ISSUE TITLE
There are more lower overhead solution than Netty

### ISSUE THREAD

**Issue by sirinath** [atomix/atomix#1079]
**Is your feature request related to a problem? Please describe.**

Netty is not the most efficient of network libraries. So using it does come at some overhead.

**Describe the solution you'd like**

Is it possible to implement the network communication stack internally to get more performance?

**Comment by johnou** [comment]
Can you provide profiling snapshots showing where Netty is a performance bottleneck?

**Comment by sirinath** [comment]
Following libraries are more lightweight:
- https://activej.io/net.html
- https://github.com/OpenHFT/Chronicle-Network

**Comment by johnou** [comment]
I didn't ask for suggestions on different libraries, if you can provide a profiling snapshot which clearly demonstrates Netty is a performance bottleneck we can investigate further.
