### ISSUE TITLE
Document current status of this project

### ISSUE THREAD

**Issue by jalberti** [atomix/atomix#1083]
I reviewed the open issues in this project, and given that many are not responded to, and are quite basic, I feel like this project is not really active, but at the same time I see more or less recent commits in multiple branches. Also the ONOS project, active user of Atomix, is active and continues to make releases, and did upgrade to Atomix 3.1 in their 2.0 release ... https://github.com/opennetworkinglab/onos/blob/master/RELEASES.md#20---january-2019.

It would be great, if a clear and concise overview of the current branches, their current status, and also any shortcomings, known issues, if that makes any sense, would be available. I.e. why would I choose one branch/release over another, what do I need to watch out for when I want to become a happy user of Atomix. Where can I contribute, making Atomix better. What can Atomix not do?

Hazelcast documentation is solid, and while Atomix has good reasons to compare itself to Hazelcast and throw shade at Hazelcasts consistency guarantees, if Atomix could invest into documentation, user guidance, especially now that Hazelcast has its own CP sub-system ... that would be greatly appreciated.

Btw. the coverage stamp is pointing to an old master branch result ... wouldn't we all wish for 97% :) ...

**Comment by osheroff** [comment]
Hi folks, I'm curious about this status here too.  I write maxwell (https://github.com/zendesk/maxwell) and am looking for a library to pull off some HA-fu.  I love the outer look of atomix's form factor; clean api, nice looking documentation, etc... but I've found that under the hood, the examples aren't working properly, the documentation is out of date, and no commits since April....

I'd be happy to continue barging ahead and possibly contribute back upstream, but I'm a bit nervous that the project has died along the way somewhere.

**Comment by mghazaryan** [comment]
Hi guys. Same here: would like to understand what the current status of the project is. We're trying to find a distributed coordination framework for Java which could be embedded (as opposed to having to bring up an external Zookeeper cluster). I had played with Atomix previously and remember how well documented it was: one could find a bunch of resources to start and play with on https://atomix.io. Now it looks like the accompanying site is broken or something: it immediately redirects you to https://atomix.io/latest/ (and the latest version appears to be 0.0.1 for some weird reason). Moreover you come across an empty page whichever link you try to open: "Getting Started", "Concepts", "User Guide", "Reference", etc.

**Comment by hbswn** [comment]
Maybe this is the reason?

- [Intel Takeovers The Open Networking Foundation’s Team](https://www.opensourceforu.com/2022/04/intel-takeovers-the-open-networking-foundations-team/)
- [Intel acquires the Open Networking Foundation's team](https://www.convergedigest.com/2022/04/intel-acquires-open-networking.html)
- [Intel® Network Builders - Open Standards](https://networkbuilders.intel.com/intel-technologies/openstandards)
- [ONF Enters a New Era Focused on Growing Adoption and Community for its Leading Open Source Projects](https://opennetworking.org/news-and-events/press-releases/onf-enters-a-new-era-focused-on-growing-adoption-and-community-for-its-leading-open-source-projects/)
- [Intel quietly buys software-defined private 5G network provider Ananki](https://rcrwireless.com/20220413/software-defined-networking-sdn/intel-quietly-buys-software-defined-private-5g-network-provider-ananki)
- [Intel acquires ONF dev team as foundation adopts new operating model](https://www.fiercetelecom.com/telecom/intel-acquires-onf-dev-team-foundation-adopts-new-operating-model)
