### ISSUE TITLE
ClassNotFoundException on io.atomix.group.DistributedGroup in atomix-all 1.0.0-rc2

### ISSUE THREAD

**Issue by joachimdb** [atomix/atomix#149]
joachimdb 10:08
Quick question: is atomix-group part of atomix-all? (I've got a ClassNotFoundException on io.atomix.group.DistributedGroup after including io.atomix/atomix-all "1.0.0-rc2")

electrical 10:51
It should yeah but not behind a computer now.

joachimdb 10:54
strange, as far as I can see I can include all implementations of io.atomix.resource except DistributedGroup
which is the one I want 

electrical 11:06
Looks like a bug then. Could you open an issue ? Can have a look later.

**Comment by electrical** [comment]
Did a quick check and you are right. Is fixed in the master branch. You could build your own version or wait for a next release.

**Comment by joachimdb** [comment]
Great. When is the new release planned?

**Comment by electrical** [comment]
@jhalterman @kuujo can you guys chime in?

**Comment by joachimdb** [comment]
As a follow up: I can still use most of the functionality as documented here: http://atomix.io/atomix/api/latest/index.html?io/atomix/coordination/DistributedGroup.html

However, some methods don't work (e.g. election)

=> Probably some cleanup of deps and docs needed after a refactoring or sth?

**Comment by kuujo** [comment]
We have a couple more pull requests to merge today and probably tomorrow and then will be pushing another release. One of the pull requests is a major cleanup of DGroup.
