### ISSUE TITLE
Opening a replica may never complete or complete exceptionally

### ISSUE THREAD

**Issue by joachimdb** [atomix/atomix#155]
(in clojure)

```
    (def r1 (-> (AtomixReplica/builder (Address. "localhost" 8010) [(Address. "localhost" 8010) (Address. "localhost" 8011)])
                (.withTransport (NettyTransport.))
                (.withStorage (Storage.))
                (.build)))
    (def r2 (-> (AtomixReplica/builder (Address. "localhost" 8011) [(Address. "localhost" 8010) (Address. "localhost" 8011)])
                (.withTransport (NettyTransport.))
                (.withStorage (Storage.))
                (.build)))

    (def pending-opens (pmap #(.open %) [r1 r2]))
```

Then `pending-opens` are futures that sometimes complete, sometimes do not complete, and sometimes complete exceptionally with trace

```
1. Caused by java.lang.IllegalStateException
   not a member of the cluster

             ClusterState.java:  380  io.atomix.copycat.server.state.ClusterState/lambda$join$52
                           nil:   -1  io.atomix.copycat.server.state.ClusterState$$Lambda$68/1683298992/accept
        CompletableFuture.java: 1298  java.util.concurrent.CompletableFuture$WhenCompleteCompletion/run
        CompletableFuture.java:  193  java.util.concurrent.CompletableFuture/postComplete
        CompletableFuture.java: 2345  java.util.concurrent.CompletableFuture/complete
          NettyConnection.java:  162  io.atomix.catalyst.transport.NettyConnection/lambda$handleResponseSuccess$3
                           nil:   -1  io.atomix.catalyst.transport.NettyConnection$$Lambda$97/1345602424/run
                Runnables.java:   20  io.atomix.catalyst.util.concurrent.Runnables/lambda$logFailure$17
                           nil:   -1  io.atomix.catalyst.util.concurrent.Runnables$$Lambda$9/922788052/run
                Executors.java:  511  java.util.concurrent.Executors$RunnableAdapter/call
               FutureTask.java:  266  java.util.concurrent.FutureTask/run
ScheduledThreadPoolExecutor.java:  180  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask/access$201
ScheduledThreadPoolExecutor.java:  293  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

```

**Comment by kuujo** [comment]
@joachimdb question: are both of the replicas being started with the same storage directory? If so, this could be the cause. Each replica needs a unique storage directory to which to store state, including the cluster configuration. So, if two replicas are writing to and reading from the same directory on the same machine then they will conflict with one another. The storage configuration should be configured with separate directories per replica when running on the same machine:
```java
Storage storage = new Storage("replica-1");
```
or
```java
Storage storage = Storage.builder()
  .withDirectory(new File("replica-1")
  .build();
```

**Comment by kuujo** [comment]
BTW you could also set `MEMORY` storage for testing to resolve these types of issues:
```java
Storage storage = new Storage(StorageLevel.MEMORY);
```

**Comment by joachimdb** [comment]
I tried both `new Storage("replica-i")` and `new Storage(StorageLevel.MEMORY)`. Neither solves the problem: `pending-opens` never complete most of the time.

**Comment by joachimdb** [comment]
Tested against master. Opening and closing succeed when starting from scratch. However, opening a previously closed replica doesn't complete. Removing the disk storage dirs fixes the problem. (see also #156)

**Comment by kuujo** [comment]
Replicas are not designed to be reusable. That should be documented, but `CopycatServer` cannot currently be `stop`ped and re`start`ed. There's a ton of state that would have to be reset.

**Comment by kuujo** [comment]
Actually, I suppose it should throw an exception.

Even though `CopycatServer` cannot be restarted, we can make replicas capable of being closed and opened simply by constructing another server from the builder.

**Comment by joachimdb** [comment]
I didn't necessarily mean the *same* replica, rather opening a fresh instance on the same directory. But after testing again it seems to work now, strange. 

Feel free to close.

**Comment by jhalterman** [comment]
TODO: throw `IllegalStateException` when attempting to start a stop'ed replica.
