### ISSUE TITLE
Problems compiling the Leader Election example

### ISSUE THREAD

**Issue by jsavlov** [atomix/atomix#181]
The "leader election" example provided in the readme seems to be broken... This error keeps occurring:

> [ERROR] Failed to execute goal on project atomix-resource-manager: Could not resolve dependencies for project io.atomix:atomix-resource-manager:bundle:1.0.0-SNAPSHOT: Failure to find io.atomix.catalyst:catalyst-netty:jar:1.0.8-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

It seems catalyst-netty 1.0.8-SNAPSHOT doesn't exist... However, we changed it to 1.0.9-SNAPSHOT in the pom.xml file and it compiled correctly.

**Comment by kuujo** [comment]
Yeah Catalyst version was bumped. Will just bump Atomix to Catalyst 1.0.8. Thanks!
