### ISSUE TITLE
Release of atomix-testing

### ISSUE THREAD

**Issue by mnicky** [atomix/atomix#183]
Would you consider releasing `atomix-testing` into the maven central? Although it doesn't contain anything complicated that man couldn't write on his own, why would someone do that when someone else (you :) have already written it? ;)

Thanks.

**Comment by kuujo** [comment]
Sure sounds like a good idea!

**Comment by jhalterman** [comment]
Agree - it should be in central.

**Comment by davidmoravek** [comment]
Hi, any estimate when you're gonna release this? It would be awesome for us to finally get rid of local dependencies :) Thanks

**Comment by kuujo** [comment]
I'm working on it right now. After tests run again I'll push a new release.

**Comment by davidmoravek** [comment]
Thanks!

**Comment by mnicky** [comment]
Thank you!

**Comment by kuujo** [comment]
Thanks for closing this :-)
