### ISSUE TITLE
missing sources in atomix-all maven artifact version 1.0.0-rc9

### ISSUE THREAD

**Issue by sclausen** [atomix/atomix#201]
in the atomix-all maven artifact, the sources are missing for some classes (e.g. Storage)

**Comment by kuujo** [comment]
Storage is a Copycat class. Should the sources from Copycat be in the atomix-all artifact?

**Comment by sclausen** [comment]
No, not directly in atomix-all, but atomix-all uses copycat 1.1.4 and they aren't included there.
![copycat](https://cloud.githubusercontent.com/assets/916076/17430801/b35380e4-5af6-11e6-83d8-44b5da3423a8.png)

**Comment by sclausen** [comment]
If I look into the jar files in `.m2/repository/io/atomix/{artifact}/1.0.0-rc9/`, no sources are attached except for `atomix-all-1.0.0-rc9-sources.jar` containing only the sources for AtomixBundle.java. Every other artifact like copycat, catalyst and all atomix-* artifacts etc. have no sources.

**Comment by SerialVelocity** [comment]
+1. This is really affecting us too. Since all the classes are decompiled instead, we have no JavaDoc.

**Comment by jhalterman** [comment]
So source jars for all atomix things should be present in maven central:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.atomix%22

Similar for Copycat, which is actually where Storage.java lives (in copycat-server):

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.atomix.copycat%22

It's worth noting that atomix-all is mostly an aggregator of other dependencies though, so classes/source lives primarily in other artifacts. I discussed this a bit [here](https://github.com/atomix/atomix/issues/212#issuecomment-271778464).
