### ISSUE TITLE
Atomix consumes 100% CPU on Google Cloud Platform, normal on local machine

### ISSUE THREAD

**Issue by psyklopz** [atomix/atomix#209]
I've built my application as an executable JAR.  I source Atomix from Maven:
        <dependency>
            <groupId>io.atomix</groupId>
            <artifactId>atomix-all</artifactId>
            <version>1.0.0-rc4</version>
        </dependency>

My local machine is running Fedora 25, with Oracle Java:
$: java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

The Google Cloud VM is running Ubuntu 16.04, with the same version of Oracle Java:
$: java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

I'm not sure what the difference in environments could be?  Or what I else I can do to help troubleshoot things...

**Comment by psyklopz** [comment]
I upgraded to rc9, and experience the same issue there as well.  I use MAPPED storage and the netty transport.

**Comment by kuujo** [comment]
This issue should be fixed with atomix/copycat#247 which should be released along with a new Atomix release in the next couple days

**Comment by jhalterman** [comment]
@psyklopz Can you retest with atomix-1.0.0?
