### ISSUE TITLE
Need for value listeners/watchers

### ISSUE THREAD

**Issue by santospm** [atomix/atomix#211]
After thoroughly going through the APIs, I've come to conclude that there's no way to get notified when a value changes.  I was expecting atomix to have it as other technologies (like Zookeeper, etcd, etc) have it.  The workaround I have so far is to poll the value every couple of seconds, while keeping a copy in memory, and comparing for changes.  It would be way nicer if the atomixReplica would get notified whenever a change has happened.

**Comment by jhalterman** [comment]
Hey @santospm 

Atomix does have event hooks in the various resources. In `DistributedValue`, for example:

http://atomix.io/atomix/api/latest/io/atomix/variables/AbstractDistributedValue.html#onChange-java.util.function.Consumer-

These event hooks are intended to be a more friendly way of learning about state changes than ZooKeeper's watchers.

**Comment by kuujo** [comment]
> I've come to conclude that there's no way to get notified when a value changes

Just write your own resource and publish all the events you want ;-)

I'm just kidding don't do that. In all seriousness, the facility for getting whatever events we want from resources are built in to Copycat, so adding arbitrary events to resources is trivial (this was done for `DistributedValue` a few days ago - https://github.com/atomix/atomix/commit/3ea2d6f5a0979114d92d817e94a0b22cd27c5557). Obviously, the coordination resources like locks and membership groups already use events for their respective features. So, I'm assuming you're referring to resources like `DistributedValue` or `DistributedMap` change events. I'll try to submit a PR for the rest of those types of events tonight or tomorrow.

**Comment by kuujo** [comment]
Polling is basically never the right thing to do in Atomix. We can add all the custom state change events we want. So, here's what will be added right now. Let me know if anything seems to be missing:
* `DistributedValue`/`DistributedLong` change events
* `DistributedMap`/`DistributedMultiMap` create, update, remove events
* `DistributedQueue`/`DistributedSet` add/remove events

**Comment by santospm** [comment]
That seems to cover all of my use cases so far.  Thanks!

**Comment by kuujo** [comment]
These are in *master* now: #214
