### ISSUE TITLE
Missing source attachment in atomix-all

### ISSUE THREAD

**Issue by ccleve** [atomix/atomix#212]
atomix-all doesn't have a source attachment. The problem is likely that the pom omits this from the 
```xml
> <build>:
>       <plugin>
>         <groupId>org.apache.maven.plugins</groupId>
>         <artifactId>maven-source-plugin</artifactId>
>         <version>${maven.source.plugin.version}</version>
>         <executions>
>           <execution>
>             <id>attach-sources</id>
>             <phase>verify</phase>
>             <goals>
>               <goal>jar-no-fork</goal>
>             </goals>
>           </execution>
>         </executions>
> </plugin>
> 
```
... but I haven't tried it.

**Comment by jhalterman** [comment]
Hi @ccleve 

`atomix-all` is kind of just a convenience dependency for Maven users that [combines](https://github.com/atomix/atomix/blob/master/all/pom.xml#L30-L39) the `atomix` and `catalyst-netty` artifacts into a single dependency. So the atomix sources and javadoc can be found under the atomix dependency:

http://repo1.maven.org/maven2/io/atomix/atomix/1.0.0-rc9/

The `atomix` dependency, in turn, pulls in a few other dependencies, such as the various resources:

https://github.com/atomix/atomix/blob/master/core/pom.xml#L21-L50

The sources/javadoc jars for those can be found in the associated locations. Does that solve your problem?

**Comment by ccleve** [comment]
It does solve the problem. Thank you.
