### ISSUE TITLE
Async way to send direct messages

### ISSUE THREAD

**Issue by hazemkmammu** [atomix/atomix#220]
`group. member("foo") ` returns null when the node with persistent member id "foo" has failed/crashed. So there is no way to send a direct message to "foo" until it rejoins the group.

Please consider introducing an option by which I can queue a message for a persistent member that can rejoin in the future.

**Comment by kuujo** [comment]
This is already fixed in `master`: #217

**Comment by jhalterman** [comment]
@hazemkmammu Look for a release with this fix shortly.
