### ISSUE TITLE
Replace server configuration with Typesafe Config

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#237]
Configuration of the Atomix server should be replaced with the [Typesafe Config](https://github.com/typesafehub/config) framework. This would allow servers to be configured in a variety of formats and support more complex configurations than are easily supported via properties files (e.g. JSON or YAML).

**Comment by jhalterman** [comment]
Typesafe Config supports HOCON, which is not quite YAML, but similar. An alternative would be to just support YAML, via Jackson or whatever.

**Comment by kuujo** [comment]
I realized that right after I typed that. I like Typesafe Config because it
doesn't require one specific configuration language, but there are
certainly arguments against that. I'm not opposed to just doing YAML, and
if Dropwizard can be used in the HTTP API then that would make sense. But I
think it may be overkill. Jackson would be fine though.

**Comment by jhalterman** [comment]
Typesafe supporting multiple languages is cool, but since you're basically just looking at HOCON or JSON, and JSON kinda sucks for config (compared to HOCON or YAML), you may as well just consider it between those two.

**Comment by electrical** [comment]
YAML is fairly easy to generate with most configuration management tools out there. My vote would go to that.
