### ISSUE TITLE
cluster graceful shutdown / restart 

### ISSUE THREAD

**Issue by lkolek** [atomix/atomix#256]
Hello,
while researching atomix, I try to make simple scenario:

1. (re)start cluster (of 3 instances),
2. get DistributedMap and put some unique k/v pairs there (e.g. 10k pairs),
3. shutdown cluster.
4. go to 1.

I have 2 issues here:
- if I shutdown all 3 instances at the same time (without .join()) it works. If I try to shutdown it one by one, the last operation hangs.
- after several runs, I cannot start the cluster. 
So my question is:
- is that kind of scennario (full cluster stop/start) supported by atomix?
- if so, how it should be performed?

**Comment by lkolek** [comment]
More observations:
1. When there are 3 different JVM processes, cluster starts much better,
2. Still, with large number of commands in log, not always node(s) can start,
3. It might (or not) have something either with time needed to apply all commands to state machine or with snapshot / log compactation. Some times the last step is snapshot writing, then on another restart of that node it works.

**Comment by johnou** [comment]
@lkolek would you please provide thread dumps of the hanging nodes?
