### ISSUE TITLE
Question - best way to detect when safe to shut down a node during rolling update

### ISSUE THREAD

**Issue by keenon** [atomix/atomix#261]
Hello all,

First of all, great library! I'm still getting my feet wet, but so far this is a beautiful piece of code.

Here's my challenge: I have a (small -- 3 nodes) cluster of VMs running a JVM server that have embedded AtomixReplicas, and I want to gracefully handle rolling updates. I've got the cluster to bootstrap and grow automatically as nodes are added by using SQL as a locking and discovery mechanism when new nodes boot up, but I'm struggling with the best way to detect when enough new nodes in a cluster have replicated the Copycat state-machine and it's safe to shutdown an old node. My current method is to check the Cluster.members() collection, and count the number of ACTIVE and AVAILABLE nodes, and block shutdown until that passes a certain threshold (noting changes with listeners on Cluster). However, it *seems* in my tests (and I may be misinterpreting the log output because I'm new to the library) that a Member becomes ACTIVE and AVAILABLE before it has replicated the full state-machine, and so shutdowns are happening before replacements are ready. Is there a better/recommended way to handle this? Am I already doing it right, and I'm just misreading the logs?

Thanks in advance, and keep up the good work! Really enjoying the library 👍

**Comment by kuujo** [comment]
Good question. TBH this needs to be built into Atomix, but it's not. Currently, a node can join the cluster without being caught up, and you're right that it's not safe to shut down too many nodes until new nodes are caught up. There's no way to determine when that happens right now. Member statuses won't reflect whether a node is caught up to the leader.

I don't have any good answers. This is easy to implement in Atomix but just hasn't been.

**Comment by keenon** [comment]
Fair enough. Thanks for the answer. I may find myself plinking around in the source in the next week or so, and if I do I'll submit a PR for this. Any pointers for where to start would be greatly appreciated.

Follow up question: is it at least possible for a node (AtomixReplica) to know when it itself is caught up after joining a cluster? For example, by issuing a small write upon joining the cluster and waiting for it to complete (as a byproduct of the blocking behavior when a new node joins a RAFT cluster) can you be guaranteed that you are now up to date? I'm not sure how Atomix handles this, and if the node is effectively PASSIVE when it joins and so the write is just sent to the master and doesn't block, but that would be an effective signal that I could use to hack around this using the same SQL mechanisms I'm using to bootstrap the cluster, if it's actually how the system behaves.

**Comment by johnou** [comment]
@kuujo taken care of in https://github.com/atomix/atomix/tree/join-catchup?
