### ISSUE TITLE
Message serialization

### ISSUE THREAD

**Issue by donmendelson** [atomix/atomix#27]
First, I want to mention two issues I have noticed with alleycat message serialization:
- When I run my unit tests as part of a Maven build, it logs an exception:

```
[copycat-cluster-2] ERROR net.kuujo.copycat.util.ExecutionContext - An uncaught exception occurred: {}
net.kuujo.alleycat.SerializationException: cannot serialize unregistered type: class net.kuujo.copycat.raft.rpc.PollRequest
    at net.kuujo.alleycat.Alleycat.writeObject(Alleycat.java:448)
```

However if I run the unit tests individually, they work correctly. Evidently, the alleycat classes are not getting registered in time in the first case. I'm not clear on when that happens in the process.
- I was unsuccessful in getting my own classes to serialize with alleycat in combination with the ones registered by copycat's "services" resource. Alleycat documentation shows that you can have more than one resolver, but I don't see a way to get that to work with copycat. The builder of NettyCluster and TestCluster create a new Alleycat instance with a resolver and don't expose it so you can register classes with it.

At high level, I am concerned about the performance of message serialization that depends on reflection to locate a serializer and also creates new objects for every message. This could result in gc issues down the line.

As an alternative, would it be possible to plug in message encoders/decoders that implement a flyweight pattern over message buffers. Then you would only need one instance of 
PollRequestDecoder, for example, not an object of every message sent and received. For an example of such serialization see https://github.com/real-logic/simple-binary-encoding

**Comment by kuujo** [comment]
Awesome! Thanks. I'm looking at this right now... Are you using the latest master?

Serialization does *not* depend on reflection to locate serializers. Reflection has been removed, and instead Alleycat provides a `SerializableTypeResolver` interface for locating serializable types, and by default it uses `ServiceLoaderResolver`:
https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/ServiceLoaderResolver.java
https://github.com/kuujo/copycat/blob/master/core/src/main/resources/META-INF/services/net.kuujo.alleycat.AlleycatSerializable

Nor does serialization necessarily create new objects for each message. In addition to pooling buffers, Alleycat is designed to recycle any object that implements the `ReferenceCounted` interface, and all of Copycat's internal requests/responses implement this interface:
https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/util/ReferenceCounted.java
https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/util/ReferencePool.java
https://github.com/kuujo/copycat/blob/master/raft/src/main/java/net/kuujo/copycat/raft/rpc/Request.java#L26
https://github.com/kuujo/copycat/blob/master/raft/src/main/java/net/kuujo/copycat/raft/rpc/Response.java#L27

Objects that implement `ReferenceCounted` and `AlleycatSerializable` are automatically pooled by Alleycat:
https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/serializers/AlleycatSerializableSerializer.java#L72

**Comment by kuujo** [comment]
By the way, I encourage you to look through the Alleycat code and open issues for any performance problems you see:
[Alleycat.writeObject](https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/Alleycat.java#L491)
[Alleycat.readObject](https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/Alleycat.java#L704)

Any remaining reflection done by Alleycat is done solely in the `SerializableTypeResolver` I linked to above. They're then stored in the [SerializerRegistry](https://github.com/kuujo/alleycat/blob/master/src/main/java/net/kuujo/alleycat/SerializerRegistry.java) where their type IDs, serializers, and other info are looked up during serialization.

**Comment by donmendelson** [comment]
Thanks for yours answers -- I feel better now. I see that you upgraded to alleycat 0.4. I updated my build. Interestingly I still get an exception when I run tests through Maven, though, but they run OK standalone. When are classes resolved?

Here's a stack trace since line numbers have changed.
```
net.kuujo.alleycat.SerializationException: cannot serialize unregistered type: class net.kuujo.copycat.raft.rpc.PollRequest
	at net.kuujo.alleycat.Alleycat.writeObject(Alleycat.java:521)
	at net.kuujo.alleycat.Alleycat.writeObject(Alleycat.java:458)
	at net.kuujo.alleycat.Alleycat.writeObject(Alleycat.java:396)
	at net.kuujo.copycat.cluster.TestRemoteMember.lambda$send$7(TestRemoteMember.java:91)
	at net.kuujo.copycat.cluster.TestRemoteMember$$Lambda$73/259967693.run(Unknown Source)
	at net.kuujo.copycat.util.ExecutionContext.lambda$wrapRunnable$3(ExecutionContext.java:115)
	at net.kuujo.copycat.util.ExecutionContext$$Lambda$17/346861221.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

**Comment by donmendelson** [comment]
Here are observations: It appears that the alleycat resolver is working ok, and Alleycat object gets cloned to each *remote* member. If client connects to a TestCluster withMemberId()  such that the client attempts to use a local member, then the exception is thrown. But connecting to a different test cluster works.

Local members do not get the serializers apparently. I'm not clear on the functionality of local member versus remote member -- documentation would be helpful. I still don't know why this exception would sometimes happen intermittently with identical code.

**Comment by kuujo** [comment]
Yeah that's interesting. Thanks for the feedback! 

This seems like it must be a bug in cloning the serializer. Really, what *should* happen is the serializer should be loaded once, and serializers should be resolved once (per node in the TestCluster). Alleycat instances are not thread safe, so Copycat copies the Alleycat instance and its serializer registry for each thread. It does the same for all internal threads as well (note that serializers themselves are not cloned and are stateless and therefore thread safe, aside from the pooled deserializer which uses a thread safe pool). But it sounds to me like clone() is missing something, right?

I am not sure why, but I haven't been able to reproduce this yet. I'll keep trying.

**Comment by donmendelson** [comment]
I haven't seen serialization problems since Revision: b6daeabf2087f787be0430999e4f4a4e31d4cefd
