### ISSUE TITLE
onChange and set().thenRun not working in 1.0.8?

### ISSUE THREAD

**Issue by j94305** [atomix/atomix#271]
I have just started trying Atomix with some very basic examples, and to my surprise, some very elementary features do not seem to work. Is it me or is that a known issue with Atomix 1.0.8?

The single-node "cluster" is created this way (I tried to do all by the book, packed it into static main methods for the sake of simplicity):

Attachment 1: AtomixClusterNode.java

Then I run a client against this node.

Attachment 2: AtomixTest.java

The interesting thing is that if I clean out all storage directories and start the cluster fresh, then the listener, the onChange will fire for every other client call setting a value. Also, in the client setting stuff, the set(...).thenRun(...) is executed properly.

At some point, the listener will exit, so I start it again. Now, it won't get any updates anymore. At the same time, the set(...).thenRun(...) lambda won't be executed anymore. The get().thenAccept(...) work fine in either case.

This is deterministic behaviour on my test system with JDK 1.8u144 on Windows 10 64bit version 1703 build 15063.540. Atomix is version 1.0.8, Catalyst version 1.2.1, Copycat 1.2.8, kryo 4.0.1, netty 4.1.5.Final.

Am I missing something obvious or is this a bug I ran into?

Thanks,
--J.

PS: Formatting a block quote with code is a pain. Attaching files is also a pain. Grrrrrrrr!

PPS: @johnou, many thanks for pointing out how to make that at least look prettier. Now, let's see what is wrong with the code - or the Atomix package.

Attachment 1:

```java
import io.atomix.AtomixReplica;
import io.atomix.catalyst.transport.Address;
import io.atomix.catalyst.transport.Transport;
import io.atomix.copycat.server.storage.Storage;
import io.atomix.catalyst.transport.netty.NettyTransport;

public class AtomixClusterNode {

    private static long t0 = System.currentTimeMillis();

    public static void info(String text) {
	System.out.println(System.currentTimeMillis() - t0 + "\t: " + text);
    }

    public static void main(String args[]) {

	try {
	    int port = args.length == 0 ? 8700 : Integer.parseInt(args[0]);

	    Transport transport = new NettyTransport();

	    Storage storage = new Storage("./s" + port);
	    AtomixReplica node = AtomixReplica
		.builder(new Address("10.0.0.40", port))
		.withStorage(storage)
		.withTransport(transport)
		.build();
	    info("Prepared atomix node");

	    if (port == 8700) {
		info("Starting primary");
		node.bootstrap().join();
		info("Started primary");
	    } else {
		info("Starting secondary");
		node.join(new Address("localhost", 8700));
		info("Started secondary");
	    }

	    Thread.sleep(3600000);
	
	    info("Leaving the cluster");
	    node.leave();
	    info("Shutting down");

	} catch (Exception e) {

	    info("Something is wrong:");
	    e.printStackTrace(System.out);
	}
	
	System.exit(0);
    }

}
```

Attachment 2: AtomixTest.java

```java
import io.atomix.AtomixClient;
import io.atomix.catalyst.transport.Address;
import io.atomix.catalyst.transport.Transport;
import io.atomix.catalyst.transport.netty.NettyTransport;
import io.atomix.variables.DistributedValue;
import java.util.concurrent.CompletableFuture;

public class AtomixTest {

    private static long t0 = System.currentTimeMillis();

    public static void info(String text) {
	System.out.println(System.currentTimeMillis() - t0 + "\t: " + text);
    }
    
    public static void main(String args[]) {

	try {
	    int port = args.length == 0 ? 8700 : Integer.parseInt(args[0]);

	    Transport transport = new NettyTransport();

	    AtomixClient client = AtomixClient.builder()
		.withTransport(transport)
		.build();
	    info("Prepared atomix client");

	    client.connect(new Address("10.0.0.40", port)).join();
	    info("Connected to cluster");

	    DistributedValue<String> value = client.<String>getValue("item").join();

	    if (args.length < 2) {
		// AtomixTest PORT
		info("Get the stored value");
		value.get().thenAccept(result -> {
			info("** value: " + result);
		    });
		
	    } else if (args[1].equals("-")) {
		// AtomixTest PORT -
		info("Listen to changes");
		value.onChange(event -> {
			info("** change: " + event.oldValue() +
			     " => " + event.newValue());
		    });
		Thread.sleep(60000);

	    } else {
		// AtomixTest PORT NEWVALUE
		info("Set a new value: " + args[1]);
		value.set(args[1]).thenRun(() -> {
			info("** value set");
			value.get().thenAccept(result -> {
				info("** verified: " + result);
			    });
		    });
		info("Getting the value set immediately");
		value.get().thenAccept(result -> {
			info("** found: " + result);
		    });
		Thread.sleep(2000);
		info("Getting the value set after two secs");
		value.get().thenAccept(result -> {
			info("** now: " + result);
		    });
	    }
	    
	    info("Back in main...");
	    Thread.sleep(3000);
	    info("Close connection");
	    client.close();

	} catch (Exception e) {

	    info("Something is wrong:");
	    e.printStackTrace(System.out);
	}
	
	System.exit(0);
    }
}
```

**Comment by j94305** [comment]
Not pretty but it has now all important bits and pieces in there...

**Comment by johnou** [comment]
@j94305 try wrapping it with markdown.. 

\`\`\`java
your code
\`\`\`

**Comment by j94305** [comment]
I tried the KeyValueStore example from here: https://github.com/jhalterman/jodah/tree/master/key-value-store
This does not use Atomix but is only based on Copycat. It basically shows the same problem, however, the simplistic code is friendly enough to throw some exceptions. In particular, the KeyValueStore.publish(...) method will not finish looping through notifications if one of them fails. So, if one of the sessions is invalid, the whole event notification loop will fail.

Changing the respective method to something like

```    private void publish(String event, Object key, Object oldValue, Object newValue) {
	listeners.forEach(c -> {
		long id = -1;
		try {
		    id = c.session().id();
		    info("Notify session " + id);
		    c.session().publish(event, new EntryEvent(key, oldValue, newValue));
		} catch (IllegalStateException e) {
		    if (id < 0) {
			info("** no session: " + e.toString());
		    } else {
			info("** session dead " + id + " - " + e.toString());
		    }
		    listeners.remove(c);
		}
	    });
    }
```

(yes, I have mastered the art of code inclusion now) will fix the issue. There are still some lags in some cases where maybe other timeouts occur, but catching exceptions on the level of individual, per-event notifications will help.

I don't really have time to dive into the Atomix code to verify this issue also occurs there, but given the similarly wrong behaviour before, and the correct behaviour after the fix, it suggests there may be a similar reason for what I noticed with the Atomix sample program.

--j.

**Comment by kuujo** [comment]
This is a bug. I'm not sure if it still exists in Atomix 2. The session should _never_ be closed when an associated command is applied to the state machine. I suspect this is a product of the previous log compaction algorithm in Copycat which can compact sessions from the log and retain commands. Copycat has been rewritten in Atomix 2 to replace these complexities of incremental compaction with snapshotting. I'm no longer maintaining Copycat or Atomix 1.x since the Atomix 2.x Raft implementation is complete. I only get paid to maintain one of them. But I will accept PRs for them and will still release bug fixes.

This issue will be closed if it can't be reproduced in Atomix 2 and nobody intends to fix it in Atomix 1.

**Comment by j94305** [comment]
Fair enough. My life won't depend on it. I'll have a look at how this behaves in Atomix 2 when I have time.

Thanks much for your feedback!
