### ISSUE TITLE
Blocked Attempting to Write to Queue Resource

### ISSUE THREAD

**Issue by manolama** [atomix/atomix#275]
Hello, first time user and I apologize if I've missed something from the docs/tutorials. I'm trying to create a queue resource and it's wedged simply inserting an object into the queue. AFAIK the queue is successfully initialized and open but the future is never given a result when waiting for a write.

```
try {
        System.out.println("Starting...");
        NettyTransport t = new NettyTransport();
        //LocalServerRegistry lsr = new LocalServerRegistry();
        //Transport transport = new LocalTransport(lsr);
        builder = AtomixReplica.builder(new Address("localhost", 8700))
            .withStorage(Storage.builder()
                .withStorageLevel(StorageLevel.MEMORY)
                .build())
            .withTransport(t);
        System.out.println("Built, now bootstrapping....");
        replica = builder.build().bootstrap().join();
        System.out.println("Bootstrapped, making me queue...");
        queue = replica.<DummyQuery>getQueue("javaBench").get();
        System.out.println("Done with init.");
        System.out.println("Is open? " + queue.isOpen());
        System.out.println("Size: " + queue.size().join());
        DummyQuery q = new DummyQuery();
        q.priority = 42;
        queue.offer(q).join();
        System.out.println("If we get here, all is well with the world...");
      } catch (Throwable t) {
        t.printStackTrace();
      }
```

It waits at the ``queue.offer(q).join();`` as per the stack:
```
Thread [main] (Suspended)	
	Unsafe.park(boolean, long) line: not available [native method]	
	LockSupport.park(Object) line: 175	
	CompletableFuture$WaitNode.block() line: 271	
	ForkJoinPool.managedBlock(ForkJoinPool$ManagedBlocker) line: 3226	
	BlockingFuture<T>(CompletableFuture<T>).waitingGet(boolean) line: 319	
	BlockingFuture<T>(CompletableFuture<T>).join() line: 2292	
	BlockingFuture<T>.join() line: 68	
	DistPriorityQueue$AtomixTestQueue.<init>() line: 325	
	DistPriorityQueue.runAtomixTestQueue(DistPriorityQueue$Context, Blackhole) line: 108	
	DistPriorityQueue.main(String[]) line: 61	
```

I'm trying to launch the Atomix "cluster" in the JVM, not trying to join an extant cluster or anything funky like that. And I'm using 1.0.8 for this test. Any ideas would be super helpful, thanks!

**Comment by kuujo** [comment]
I don't really see anything wrong with the code. If the `bootstrap` call is returning then the rest of the code should be working. I'd suggest looking at the Atomix 1.x tests and enabling io.atomix TRACE logging to see the requests being logged. You should see a `CommandRequest` logged in a `CommandEntry` which is applied to the state machine and a `CommandResponse` returned.

**Comment by manolama** [comment]
Ahhh, that did it. So I didn't have a log implementation attached but once I threw in Logback I saw the exception that doesn't bubble up to my code:

```
11:01:12.301 [copycat-server-localhost/127.0.0.1:8700-copycat] ERROR i.a.c.concurrent.SingleThreadContext - An uncaught exception occurred
io.atomix.catalyst.serializer.SerializationException: cannot serialize unregistered type: class net.opentsdb.distobj.DistPriorityQueue$DummyQuery
	at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:864) ~[atomix-all-1.0.8.jar:na]
```

That's a bug in Atomix that should be fixed, i.e. bubble up this type of exception to the client code. In the mean time looks like I need to implement serialization for my object. Thanks!

**Comment by kuujo** [comment]
You're right. A lot of exceptions get caught in internal threads and aren't properly returned to clients. This is a little improved in Atomix 2.x but I think it still needs some work.

**Comment by manolama** [comment]
Sounds good, thanks!
