### ISSUE TITLE
Where is documentation and example? 

### ISSUE THREAD

**Issue by ade90036** [atomix/atomix#284]
Hi, 

i'm trying to test out the atomix. 
It seems to be providing a lot of the features i'm interested in.

However the README from the git project is incompleted in describing what i need to do to get up and running.

There are no example and the link from the amotix.io website (Example) is broken.

The atomix.io website seems to showing a lot of code from 1.0.0 branch which doesn't map to what is published on maven (2.0.2)

So, what is the best way for me to test this.

N.B. If you don't have the basic documentation in place such as (configuration and examples). Inevitably this project will suffer from poor adoption / uptake. 

Ade

**Comment by ade90036** [comment]
Ok, i have managed to get, at least the code to compile. 

But i have tried few examples from the atomix.io but i can't seem to get anything working. 

I have two springboot application running on localhost (port 8080 / 8081). 

How do i setup a cluster of replica from those two JVM, so i can start share data between the JVMs using DistributedMap or DitributedList or DistributedLocks. 

(Probably this would be the most common scenario)

Is there an easy initialisation code block which will automatically boostrap the first node if it needs to and joining the rest?

I would hate to have a bootstrap() code in one JVM and then have the joint() code in the other JVMs.

Ade

**Comment by GEverding** [comment]
I was curious about this issue so I took a look at what CockroachDB does. If your running in a clustered env like kubernetes they use stateful sets and a flag file to decide to start up. I can share link to examples if there code if you’re interested.

I’m curious how to setup Atomix 2.x. Can you share any code samples?
