### ISSUE TITLE
a warning of netty setting

### ISSUE THREAD

**Issue by LQ-Gov** [atomix/atomix#302]
java:1.8
netty:4.1.6
atomix-all:1.0.8
warning:Unknown channel option 'TCP_NODELAY' for channel

`      this.replica = AtomixReplica.builder(me)
                .withStorage(new Storage("data"))
                .withTransport(new NettyTransport())
                .build();`

I use NettyTransport,promt me above warning, I check the code, found use the **TCP_NODELAY** option in the **ServerBootstrap**  of netty, but ServerBootsrap no any options key about it,so can't passed,would you delete the setting in the next version? thanks

**Comment by johnou** [comment]
@LQ-Gov looks like this is fixed in master.
