### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by jplock** [atomix/atomix#321]
Which version should people be using? I see 2.1.0 in maven central but the documentation doesn’t reflect this version. It seems like there is development occurring around 2.0.7. 

I wanted to build an application on top of atomix, but I’m not sure where to get started. Thanks!

**Comment by johnou** [comment]
The 2.0 branch is just being maintained for an ONOS release. Documentation is work in progress. Atomix 2.1, and the first release is targeted for around January 1st.

**Comment by jplock** [comment]
Great, thanks!
