### ISSUE TITLE
Best way to pass around Atomix instance?

### ISSUE THREAD

**Issue by jplock** [atomix/atomix#337]
I've created a sample application at [dropwizard-atomix](https://github.com/smoketurner/dropwizard-atomix/blob/master/atomix-example/src/main/java/com/example/helloworld/HelloWorldApplication.java#L61) that tries to integrate Atomix inside of a [Dropwizard](https://github.com/dropwizard/dropwizard) application.  However, whenever `.join()` is called, the thread is blocked indefinitely and never returns an Atomix instance.  I'd like to be able to pass the Atomix instance into my Jersey resources so I can expose APIs.

I thought if [buildInstance()](https://github.com/atomix/atomix/blob/master/core/src/main/java/io/atomix/Atomix.java#L497) in  was exposed without calling `open()`, then I could wire everything up and use Dropwizard's [Managed Objects](http://www.dropwizard.io/1.2.2/docs/manual/core.html#managed-objects) to call .open() and .join().

Should .join() be returning an `Atomix` instance quickly?

**Comment by kuujo** [comment]
Hmm... I guess there are a couple options:
• Always make the user call `open()` which should probably also be renamed to `start()`
• Provide another builder method to build an unopened instance

I think we could remove the `Managed` interface from `Atomix`, change those methods to `start` and `stop`, and just return an uninitialized `Atomix` instance from the builder.

Then again, you could also just pass an `Atomix.Builder` into the DW `Managed` object and call `build()` to initialize the instance.

**Comment by kuujo** [comment]
BTW `join()` should not block indefinitely. If it's blocking indefinitely then that indicates that it's awaiting a quorum. When the instance is started, if e.g. it's configured with 3 bootstrap nodes, 2/3 nodes have to be started before the `open()` method will return. Enable `DEBUG` or `TRACE` logging and you'll likely see Raft nodes attempting to get elected over and over again. Once a majority of nodes in all partitions are able to reach each other they'll elect a leader and the `open()` call will complete.

**Comment by kuujo** [comment]
On a related note, I always forget to add this to the documentation, but just started working on the Atomix 2 documentation.

**Comment by jplock** [comment]
When starting the first node, should I specify bootstrap nodes?

**Comment by kuujo** [comment]
Good question. I don't see why that needs to be a requirement. If the node that's started is a `DATA` node and the bootstrap nodes are empty then it should form a one node cluster. TODO

I'll also improve the bootstrap documentation right now.

Basically, the "bootstrap nodes" provided to an Atomix instance's configuration should be the initial configuration for a new cluster or - if a cluster is already running and a node is being added to it - the nodes in the existing cluster. So, it should be possible to start a single node as a bootstrap node and then add additional nodes to it... but the new protocol for resizing clusters was just written last week and has a lot of testing to be done. The safest way to start a cluster is always to list the set of data nodes in the bootstrap list and start them all simultaneously.
