### ISSUE TITLE
φ (phi) timeout false positive

### ISSUE THREAD

**Issue by johnou** [atomix/atomix#366]
When running a simple stress test I received a timeout of 8 milliseconds which is far too strict.

```
Caused by: java.util.concurrent.TimeoutException: Request timed out in 8 milliseconds
at io.atomix.messaging.impl.NettyMessagingService$RemoteClientConnection.timeoutCallbacks(NettyMessagingService.java:879)
```

**Comment by johnou** [comment]
Maybe response times < 100ms should be excluded from samples..?

**Comment by johnou** [comment]
Option for disabling PHI timeout might be nice too.

**Comment by johnou** [comment]
Akka implementation uses "minStdDeviation" [1] which might help in this case.

```
 * @param minStdDeviation Minimum standard deviation to use for the normal distribution used when calculating phi.
 *   Too low standard deviation might result in too much sensitivity for sudden, but normal, deviations
 *   in heartbeat inter arrival times.
```

[1]
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/PhiAccrualFailureDetector.scala#L182

**Comment by kuujo** [comment]
That seems worth a test.

**Comment by johnou** [comment]
I'll check it out tomorrow 👍

**Comment by johnou** [comment]
Excluding reply time of zero from samples was enough for my stress test, didn't need to change the PHI calculation logic eg. factor in CV.

**Comment by johnou** [comment]
https://github.com/atomix/atomix/pull/400 is good for now.
