### ISSUE TITLE
Source codes in atomix-xxx-sources.jar do not match with the compiled classes in  atomix-xxx.jar

### ISSUE THREAD

**Issue by baymaxhuang** [atomix/atomix#370]
The atomix-xxx.jar includes many classes which are exported from other modules such as atomix-raft, atomix-storage and atomix-buffer etc.  But the atomix-xxx-sources.jar only include the souce class files in core atomix module. As a resuslt, the source codes in atomix-xxx-sources.jar do not match with compiled classes in atomix-xxx.jar. Moreover, the java IDE such as idea or eclispe could not find and download the source code jar according to the compiled atomix-xxx.jar automatically, which is not convenient for developers to read the source codes of atomix.

**Comment by johnou** [comment]
I believe this has been resolved in master by moving the atomix module into the core package.

**Comment by baymaxhuang** [comment]
Thanks, I see it. I think it is better to rename the artifactId of core module to atomix-core. And we can also publish a compiled jar and a source code jar which include all the packages in the atomix project, just like that netty-all includes netty-buffer, netty-transport, netty-handler and etc.

**Comment by johnou** [comment]
I would actually opt for a bom artifact over an uber jar to avoid conflicting versions on the class path.

**Comment by johnou** [comment]
The original problem reported should anyway be resolved. @kuujo did you want to rename the jar or leave as is?

**Comment by kuujo** [comment]
I think I prefer the simple `atomix` name to `atomix-core` because of the new dependency hierarchy where `Atomix` Is basically at the top of a diamond and already depends on all the artifacts beneath it.
