### ISSUE TITLE
Realization of φ accrual failure detector

### ISSUE THREAD

**Issue by baymaxhuang** [atomix/atomix#405]
The [PhiAccrualFailureDetector](https://github.com/atomix/atomix/blob/832df3702d1aabbbbb1a2e3e395d50b1d0e94972/cluster/src/main/java/io/atomix/cluster/impl/PhiAccrualFailureDetector.java) in Atomix is actually implemented based on the [FailureDetector](https://github.com/apache/cassandra/blob/9b828275288b135812a247c3f2e9da2f20547111/src/java/org/apache/cassandra/gms/FailureDetector.java) of Cassandra, which is a little different from the original Phi failure detector proposed in the original paper by Hayashibara et al. See: https://issues.apache.org/jira/browse/CASSANDRA-2597

**Comment by johnou** [comment]
@baymaxhuang so what's the actual problem? the implementations look very different to me, what makes you think that the Atomix implementation was based on the Cassandra code?

**Comment by baymaxhuang** [comment]
The original phi value in Hayashibara's paper is calculated based on the normal distribution, the failure detector in [Akka](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/PhiAccrualFailureDetector.scala#L173-L189) uses the original realization. However, the phi value in Atomix is calculated based on an exponential distribution, which is the same as the realization in Cassandra. The [Cassandra paper](http://www.cs.cornell.edu/projects/ladis2009/papers/lakshman-ladis2009.pdf) has mentioned why a exponential distribution is applied and there is also a discussion in [CASSANDRA-2597](https://issues.apache.org/jira/browse/CASSANDRA-2597).

**Comment by johnou** [comment]
Are you suggesting the implementation could be improved? Pull requests are welcome!

**Comment by baymaxhuang** [comment]
I think the code comment should be improved to make it more clear. The realization could remain what it was. I will pull a request.

**Comment by johnou** [comment]
@baymaxhuang good to close this issue?
