### ISSUE TITLE
What is the role of numBackups?

### ISSUE THREAD

**Issue by tanbangcheng** [atomix/atomix#442]
The default value for numBackups is 2 in DistributedPrimitiveBuilder.
A typical 3-node cluster,  when a node fails, the role of the remaining two nodes becomes NoneRole, which makes the service unavailable. 

changeRole in PrimaryBackupServiceContext
```Java
  private void changeRole(PrimaryTerm term) {
    if (term.term() > currentTerm) {
      log.info("Term changed: {}", term);
      currentTerm = term.term();
      primary = term.primary();
      backups = term.backups().subList(0, Math.min(descriptor.backups(), term.backups().size()));

      if (backups.size() < descriptor.backups()) {
        if (this.role == null) {
          log.warn("Not enough backups; transitioning to {}", Role.NONE);
          this.role = new NoneRole(this);
          log.trace("{} transitioning to {}", clusterService.getLocalNode().id(), Role.NONE);
        } else if (this.role.role() != Role.NONE) {
          log.warn("Not enough backups; transitioning to {}", Role.NONE);
          this.role.close();
          this.role = new NoneRole(this);
          log.trace("{} transitioning to {}", clusterService.getLocalNode().id(), Role.NONE);
        }
      }
    ...
}
```

Does numBackups mean there are two backups at the same time?  Did I miss something?

**Comment by kuujo** [comment]
`numBackups` is the number of _backups_ aside from the primary. So, in a two-node cluster, if a node is lost then there are not enough nodes to satisfy 1 primary plus two backups.

This actually needs to be made configurable to set a number of backups plus a _required_ number of backups. But the primary-backup protocol is work in progress.
