### ISSUE TITLE
Replication count for Collections

### ISSUE THREAD

**Issue by corporatepiyush** [atomix/atomix#448]
Is it possible to set replication factor for Distributed Collection (Map, Set, Queue) ? or they are replicated to every node in cluster ?

**Comment by kuujo** [comment]
In Atomix 1.x (which is documented on the website) there’s only one Raft cluster and Raft by its nature quorum-based and replicated to all nodes.

In Atomix 2.1 (which is currently documented  in the README) data structures can be stored either in Raft partitions or primary-backup partitions. If stored in Raft partitions, changes are normally replicated on 3/n or 5/n nodes. If stored in primary-backup partitions, you can configure the number of backups. It just depends on the primitive configuration.

Also, please ask questions on the Google Group. But maybe you did that. I’ve been in and out of town for a few weeks :-)
