### ISSUE TITLE
Support multicast based discovery of non-CORE nodes

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#462]
`CORE` type nodes must be explicitly configured with static host names, but for `DATA` and `CLIENT` nodes, multicast can be optionally used in place of bootstrap nodes. This may only be useful in a cluster that doesn’t include `CORE` nodes that require a static configuration anyways.

**Comment by kiransp1** [comment]
hi

**Comment by kuujo** [comment]
Hi.

**Comment by kuujo** [comment]
This issue can be closed
