### ISSUE TITLE
Is there a way to set timeout for ClusterMessagingService.send method?

### ISSUE THREAD

**Issue by mbaksheev** [atomix/atomix#477]
Could you explain,  Is there a way to set timeout for responce for ClusterMessagingService.send method? and what is the default timeout?
I haven't found documentation about this.

**Comment by imperatorx** [comment]
Last time I checked it was bound to the generic cluster communication which uses some kind of variance based timeout detection? 

It would be good to separate cluster messaging timeout from generic atomix timeout, right now I have to return an ack immediately, and then return a response message in a separate call with a correlation id and listen for completion on the caller side.

**Comment by johnou** [comment]
What's the use case? Could you not use a timeout on the cf?

**Comment by mbaksheev** [comment]
Thanks a lot
