### ISSUE TITLE
Can not build the Atomix object when run atomix server

### ISSUE THREAD

**Issue by MaoJianwei** [atomix/atomix#563]
Hello, 

I build a simple atomix server, but can not build the Atomix object.

![image](https://user-images.githubusercontent.com/12800168/40287339-43c60d40-5cdf-11e8-9145-6ef8ea4cef27.png)

d:\MaoDev\maoatomixsample>java -jar ./target/mao-atomix-sample-1.0-SNAPSHOT.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" io.atomix.utils.config.ConfigurationException: Unknown partition group configuration type: PrimaryBackupPartitionGroupConfig
..............at io.atomix.primitive.partition.PartitionGroups.createGroup(PartitionGroups.java:41)
..............at io.atomix.core.Atomix.buildPartitionService(Atomix.java:379)
..............at io.atomix.core.Atomix.<init>(Atomix.java:141)
..............at io.atomix.core.Atomix$Builder.build(Atomix.java:581)
..............**at com.maojianwei.test.Server.main(Server.java:41)**
 

![image](https://user-images.githubusercontent.com/12800168/40287372-832a73cc-5cdf-11e8-90b0-81feb18c8d46.png)

I use maven-shade-plugin to copy all dependency class into my built jar.
But although I specify the classpath, the problem is still here.

By the way, I use atomix 2.1.0-SNAPSHOT pulled yesterday

I got a problem here, but I don't know how to resolve it, Could you please help me?

Thanks!!

**Comment by kuujo** [comment]
Someone is here.

This should really be asked in the Google Group.

This seems to indicate some sort of dependency problem. When the Atomix object is constructed, it’s actually constructed from a configuration object, and the configuration object is used to load partition groups, primitive types, and other stuff internally. Theses extensions are loaded via a ServiceLoader, and it appears these services are not being picked up via the service loaded, presumably because the services are not found on the classpath fo some reason.

**Comment by MaoJianwei** [comment]
Thanks!  Sorry for that, but I don't find the Google group weblink for Atomix in the Readme. Could you please give me a hint?


And for this problem, I found ServicesResourceTransformer of maven-shade-plugin will cause other problems for Kryo.

So, I decide to use maven-dependency-plugin to help me resolve dependency, as follow.

Thanks Jordan 👍 

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/dependency-jars/
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by khmarbaise** [comment]
If there a ServiceLoader you have to use [service transformer](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer) which I don't see in the configuration of maven-shade-plugin which of course will result in not working correctly. Apart from that I would also recommend to use more up-to-date versions of [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/).

**Comment by kuujo** [comment]
Thanks @khmarbaise!

**Comment by kuujo** [comment]
@MaoJianwei you’re right. The Google Group was removed from the README. It’s buried in the website but needs to be in the README. Will update it.
