### ISSUE TITLE
Code doesn't match documentation

### ISSUE THREAD

**Issue by bmorris591** [atomix/atomix#570]
I suppose this is more of a question than as issue - but here goes.

Your website has a pretty thorough looking [user manual][1] (kudos), but unfortunately the API [published to Maven][2] (2.1.0-beta3) does not match this documentation.

For example the user manual talks about `Atomix.builder().withMembers(...)`, this method does not exist on the API published - that talks about `Node` rather than `Member`.

So two questions:

1. Is there anywhere a set of documentation for `2.1.0-beta3`?
2. What is the plan to bring the two into line?

[1]: http://atomix.io/docs/latest/user-manual/
[2]: https://mvnrepository.com/artifact/io.atomix/atomix/2.1.0-beta3

**Comment by kuujo** [comment]
There’s been no release since that API change, so no new Javadoc unless you pull the project and run mvn javadoc:javadoc. The API is considered unstable until the RC, which should be next week. The website will remain more up-to-date until then.

**Comment by kuujo** [comment]
This can be closed now
