### ISSUE TITLE
Unable to programmatically register custom primitive type after API change

### ISSUE THREAD

**Issue by imperatorx** [atomix/atomix#584]
The constructor which lets one set the parameters of PrimitiveType (e.g. the configClass) is private, only the no-arg one is public. I guess this is because it is intended to be used with reflection.

One can subclass the primitive type and override method like 

> public Class<C> configClass()

, but the code is checking the private variables and not the getters in some cases, making it impossible to do programmatic  registration:

    if (configClass == null) {
      throw new ConfigurationException("No configuration class specified for primitive type " + name());
    }

This would always be null without reflection.

**Comment by kuujo** [comment]
A builder is provided to set the parameters:

```java
PrimitiveType myCustomType = PrimitiveType.builder()
  .withConfigClass(MyConfigClass.class)
  .build();
```

**Comment by kuujo** [comment]
BTW this will change back to something similar to the previous method in the next couple of days, but primitive types will no longer need to be explicitly registered. Just create the primitive:

```java
public class MyPrimitiveType implements PrimitiveType<MyPrimitiveBuilder, MyPrimitiveConfig, MyPrimitive> {
  ...
}
```

```java
Atomix atomix = Atomix.builder()
  ...
  .build();

MyPrimitive myPrimitive = atomix.primitiveBuilder("foo", MyPrimitive.INSTANCE)
  ...
  .build();
```

**Comment by imperatorx** [comment]
Thank you, the builder approach works great.
