### ISSUE TITLE
Inconsistent Resource Type

### ISSUE THREAD

**Issue by spapapanagiotou** [atomix/atomix#637]
While trying to access a distributed map we are getting the following exception

inconsistent resource type: ResourceType[id=-11, factory=class io.atomix.collections.util.DistributedMapFactory]

What can be the root cause ?

Do you consider an problem that we are using the same "key" for both getMap and getKey ?
I consider them different entities and as a result this must not be a problem. Right ?

Version used: 1.0.8

Thanx !

**Comment by kuujo** [comment]
The error message indicates a resource with the same name but a different type already exists.

**Comment by spapapanagiotou** [comment]
I imagine same "name" you mean same "key" ! Hence getMap("keyName") and getMap("keyName")
will cause exception ! Right ?

**Comment by kuujo** [comment]
Yes that's right
