### ISSUE TITLE
Atomix should take a file for configuration

### ISSUE THREAD

**Issue by FKrack** [atomix/atomix#641]
Currently, the configuration file must be inside the classpath.

>Jordan Halterman @kuujo 11:04
>Yeah that’s because of the change to the configuration format. Just add atomix.conf to the classpath now. Doesn’t have to be inside a jar
>We have to add an additional method to take a File in the Atomix factories to make sure paths work correctly because Typesafe Config only tries to search the classpath if you don’t explicitly parse a file

**Comment by kuujo** [comment]
#643
