### ISSUE TITLE
How to control memory usage of log entry when StorageLevel is MAPPED

### ISSUE THREAD

**Issue by zhaozhongguo** [atomix/atomix#644]
Hi:

When the raft StorageLevel is set to MAPPED mode, if the load is always at a high level, the log compact will not be executed, and the memory will continue to grow. Should you provide an interface that configures memory usage like isRunningOutOfDiskSpace

**Comment by johnou** [comment]
@zhaozhongguo would you be willing to provide a pull request?

**Comment by johnou** [comment]
Thanks!

**Comment by zhaozhongguo** [comment]
welcome 👍
