### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by hvandenb** [atomix/atomix#65]
This is not much of an issue but rather a request to add a Atomix room on [Gitter](https://gitter.im) which might help with collaboration.

**Comment by kuujo** [comment]
Agree. I'll try to set it up tonight.

**Comment by hvandenb** [comment]
thanks I appreciate it.

**Comment by kuujo** [comment]
https://gitter.im/atomix?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jhalterman** [comment]
You forgot to add a badge to the README. That's like the whole point of having a gitter room ;)

**Comment by kuujo** [comment]
Oh yeah! Badge it up son!

**Comment by kuujo** [comment]
Sorry I messed up the chat room. Gitter noob :-) Fixing it

**Comment by kuujo** [comment]
https://gitter.im/atomix/atomix
