### ISSUE TITLE
too much netty messages & out of memory when restart one node

### ISSUE THREAD

**Issue by aruanruan** [atomix/atomix#654]
when starting 3 raft nodes by agent in one window 10.
then shut down none node, and then start it
so lots of java.util.concurrent.TimeoutException , RaftSession$$Lambda Object ....
then  os look like so busy, i can not operate it

**Comment by aruanruan** [comment]
1.  i just download the newest version from github
2.  3 config files,   /s1/atomix.conf /   /s2/atomix.conf   /s3/atomix.conf
```
cluster {  
  members.1 {
    id: member1
	host: localhost
    address: "localhost:5001"  
  }
  members.2 {
    id: member2
	host: localhost
    address: "localhost:5002"
  }
  members.3 {
    id: member3
	host: localhost
    address: "localhost:5003"
  }

}

management-group {
  type: raft
  name: system
  partitions: 1
  storageLevel: DISK
  dataDirectory: "data/member1"    ==> node2 use "data/member2", node3 using /data/member3"
  members: [member1, member2, member3]
}

partition-groups.raft {
  type: raft
  partitions: 1
  storageLevel: DISK
  dataDirectory: "data/member1"
  members: [member1, member-2, member3]
}


profiles: [consensus, data-grid]
```
3. window bat files:
/s1/run.bat
java -jar ../../target/atomix-agent.jar -c atomix.conf member1 --http-port 8081
/s2/run.bat
java -jar ../../target/atomix-agent.jar -c atomix.conf member2 --http-port 8082
/s3/run.bat
java -jar ../../target/atomix-agent.jar -c atomix.conf member3 --http-port 8083

4.AtomixAgent.java
i changed parseMemberId function to:
```
static MemberId parseMemberId(String address) {
    int endIndex = address.indexOf('@');
    if (endIndex > 0) {
      return MemberId.from(address.substring(0, endIndex));
    }
   // return null;
    return MemberId.from(address);  
  }
```

**Comment by johnou** [comment]
@aruanruan does this still occur with rc3? can you provide a heap dump?

**Comment by johnou** [comment]
Please reopen if you can reproduce the issue in the following RC.
