### ISSUE TITLE
Custom discovery service

### ISSUE THREAD

**Issue by AlexITC** [atomix/atomix#659]
From the documentation, I have seen some ways to discover nodes but I haven't seen a way to use a custom discovery service, I wonder if that is possible.

I have an existing application which is able to discover other nodes and I would like to pass or remove those nodes to atomix instead of letting atomix the node discovery.

i'm using atomix `2.1.0-beta1`.

Thanks.

**Comment by kuujo** [comment]
Good idea. This should be simple enough to do. We just need an SPI that provides member add/remove events with a TCP `Address`.

**Comment by AlexITC** [comment]
I'm not familiar with the source code, if you give me some insights I could work in a pull request.

**Comment by kuujo** [comment]
Got it handled, but I'd love to get your feedback to see if the API actually suits your use case.

**Comment by johnou** [comment]
Implemented in master, thanks for the suggestion!
