### ISSUE TITLE
Create binary distribution for Atomix agent

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#750]
**Is your feature request related to a problem? Please describe.**

Running the Atomix agent is currently a tedious task.

**Describe the solution you'd like**

Add a binary distribution for Atomix agent to facilitate running and configuring the agent.

**Comment by kuujo** [comment]
Atomix cannot depend on Java 9

**Comment by johnou** [comment]
Target could still be Java 8, https://github.com/moditect/moditect

**Comment by kuujo** [comment]
I don't see how either of those things help me. The distro needs to set up the classpath and make a runnable jar, but it also needs to set up scripts, logging directories, system logs, configuration files, license, and make sure it's easily extensible. That's not nearly enough information to do all that in the short amount of time I have to do this.

**Comment by johnou** [comment]
assembly plugin might be worth a look at then http://maven.apache.org/plugins/maven-assembly-plugin/examples/single/filtering-some-distribution-files.html
