### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by kamath-prasad** [atomix/atomix#753]
**Expected behavior**

Should be able to build the project using successfully.

**Actual behavior**

maven build ends with error

**Steps to reproduce**

On executing , `mvn clean install -Dmaven.test.skip=true` from the master branch the build ends with error , see the trace attached.
[mvn_output.txt](https://github.com/atomix/atomix/files/2253312/mvn_output.txt)

**Environment**

 - OS: `Darwin C02V64NTHTD6 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`

 - JVM 

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
-  Maven 

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
bla$ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T01:19:05+05:30)
Maven home: /Users/bla/Documents/software/apache-maven-3.5.3
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```

**Comment by johnou** [comment]
Same issue as https://www.mail-archive.com/dev@maven.apache.org/msg117278.html as a work around you can use the Maven wrapper included with Atomix.

**Comment by johnou** [comment]
https://issues.apache.org/jira/browse/MSHADE-295
