### ISSUE TITLE
Support private/public interfaces

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#785]
When running Atomix nodes in a container, often the IP to which the Atomix node binds can differ from the IP to which other nodes must connect to communicate with the node. Atomix should allow a bind address separate from the address broadcast to other nodes in the cluster.

**Comment by johnou** [comment]
@kuujo duplicate of https://github.com/atomix/atomix/pull/845?

**Comment by kuujo** [comment]
Done in 3.1
