### ISSUE TITLE
mvn package stalls on tests often

### ISSUE THREAD

**Issue by electrical** [atomix/atomix#80]
Not sure if my dev VM is just to light for it but a lot of the times the tests stall at various points.
Running with jdk1.8.0_66

Anything i can check to see why its stalled?

**Comment by jhalterman** [comment]
Hi Richard,

In general the tests take a while to run since, presently, most of the test cases setup and teardown a Raft cluster which takes a bit. I suspect there's still some work to be done to get them running more smoothly.

We just added BEFORE and AFTTER tracing to the test output yesterday to help keep tabs on individual test method performance from the output. Make sure you're on the latest commit in master and see if you can tell from the test output which test method things seem to be hanging on (should be described in the last BEFORE statement you'll see in your output).

**Comment by electrical** [comment]
Hi,

I'm on the latest master yeah.
Currently stalled on `18:41:08.353 [main] INFO  BEFORE - io.atomix.AtomixTest.testLeaderElection`

**Comment by kuujo** [comment]
I'm looking at this

**Comment by kuujo** [comment]
Alright. So, I think I found the race condition in Copycat that's causing this. I'll submit a PR with an explanation there.

**Comment by kuujo** [comment]
@electrical Atomix tests are now passing: https://travis-ci.org/atomix/atomix

**Comment by electrical** [comment]
@kuujo just pulled in the latest changes and this is the last bit i'm seeing:

```
12:36:37.682 [copycat-server-localhost/127.0.0.1:5004] INFO  i.a.c.server.state.ServerContext - Server started successfully!
12:36:37.698 [copycat-server-localhost/127.0.0.1:5002] WARN  i.a.c.server.state.LeaderAppender - localhost/127.0.0.1:5002 - Failed to configure localhost/127.0.0.1:5004
12:36:37.703 [copycat-server-localhost/127.0.0.1:5004] INFO  i.a.copycat.server.state.ServerState - localhost/127.0.0.1:5004 - Successfully joined via localhost/127.0.0.1:5001
12:36:37.704 [copycat-server-localhost/127.0.0.1:5004] INFO  i.a.copycat.server.state.ServerState - localhost/127.0.0.1:5004 - Transitioning to PASSIVE
12:36:37.815 [copycat-server-localhost/127.0.0.1:5004] INFO  i.a.copycat.server.state.ServerState - localhost/127.0.0.1:5004 - Found leader localhost/127.0.0.1:5002
12:36:37.815 [main] INFO  AFTER - io.atomix.AtomixServerTest.testServerJoin Ran for 5.338 seconds
12:36:37.823 [copycat-server-localhost/127.0.0.1:5001] INFO  i.a.copycat.server.state.ServerState - localhost/127.0.0.1:5001 - Transitioning to INACTIVE
12:36:37.827 [copycat-server-localhost/127.0.0.1:5002] INFO  i.a.copycat.server.state.ServerState - localhost/127.0.0.1:5002 - Transitioning to INACTIVE
12:36:37.828 [copycat-server-localhost/127.0.0.1:5003] INFO  i.a.copycat.server.state.ServerState - localhost/127.0.0.1:5003 - Transitioning to INACTIVE
```

and stays that way even after 10 minutes.
Not sure if its my test system or something else.

**Comment by electrical** [comment]
Seems the test suite isn't super stable. sometimes it passes. other times it stalls at random points.

**Comment by electrical** [comment]
Also seen some 
```
18:58:09.393 [copycat-server-localhost/127.0.0.1:5004] ERROR i.a.c.u.c.SingleThreadContext - An uncaught exception occurred
java.lang.OutOfMemoryError: Java heap space
```

**Comment by kuujo** [comment]
Indeed. I can produce failed tests when I run groups of them, but I can't produce the same failures but running individual tests. The same is true in Copycat. It seems to maybe be an issue with test cleanup and resource usage, and it definitely seems like tests are running into each other. Did some profiling yesterday... More today...
