### ISSUE TITLE
Additional discovery implementations?

### ISSUE THREAD

**Issue by jplock** [atomix/atomix#804]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'm interested in creating a discovery provider for Consul and another for Kubernetes.  Would you be welcome to including those as optional modules within this project, a separate project under the atomix organization or a standalone project entirely?

**Describe alternatives you've considered**

None

**Additional context**

Just looking to make it easier to launch self-forming atomix clusters using existing service discovery mechanisms.

**Comment by kuujo** [comment]
Those are common enough systems that I'm open to including them as modules of the Atomix core project. I guess we could just add a `discovery` module or something with `consul` and `kube` modules or something like that, just as is currently done with `protocols`.

**Comment by jplock** [comment]
I think that proposal makes sense.  The different discovery modules should definitely be separate as they might pull in extra dependencies.  I was thinking of using https://github.com/kubernetes-client/java for the `kube` one and https://github.com/rickfast/consul-client for the `consul` one.

**Comment by kuujo** [comment]
Yep. So I'd say feel free to add dependencies to those modules.
