### ISSUE TITLE
New Raft log

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#865]
The Jeremy implementation of the Raft log is inefficient in terms of garbage collection, throughout, etc. I’ve been working on a new implementation of the log for 3.1 which uses `FileChannel`s and memory mapped files in a manner that avoids unnecessary allocations.

**Comment by johnou** [comment]
@kuujo can this be closed or is https://github.com/atomix/atomix/pull/896 only a part of this task?

**Comment by kuujo** [comment]
Good to go
