### ISSUE TITLE
JavaDoc link broken

### ISSUE THREAD

**Issue by ashwanthkumar** [atomix/atomix#89]
http://atomix.io/atomix/api/latest/ is broken and gives a 404

**Comment by ashwanthkumar** [comment]
Sorry just now found out this is the new link - http://atomix.io/atomix/api/1.0.0/

Would be good to update the docs.

**Comment by kuujo** [comment]
Ahh thanks

**Comment by jhalterman** [comment]
Good to go. Sorry bout that.
