### ISSUE TITLE
Enable access to ServiceContext in PrimitiveService

### ISSUE THREAD

**Issue by Zelldon** [atomix/atomix#983]
**Is your feature request related to a problem? Please describe.**

We tried to implemented a custom primitive, which should write data into a logfile. 
We want to write for each primitive per partition an own logfile, currently we are not able to resolve the
partition in the primitive service. This means that all primitives on one node will write in the same file, which is not ideal.

**Describe the solution you'd like**

Would be nice if we can access in the configure phase or in general in the PrimitiveService the context,
which contains the partition information.

**Describe alternatives you've considered**

Currently we doing it via reflection:

```java
protected void configure(ServiceExecutor executor) {
    super.configure(executor);
    try {
      final Field context = DefaultServiceExecutor.class.getDeclaredField("context");
      context.setAccessible(true);
      final RaftServiceContext raftServiceContext = (RaftServiceContext) context.get(executor);
      final Field raft = RaftServiceContext.class.getDeclaredField("raft");
      raft.setAccessible(true);
      RaftContext raftContext = (RaftContext) raft.get(raftServiceContext);
      LOG.error("configure {}", raftContext.getName());
      raft.setAccessible(false);
      context.setAccessible(false);
    } catch (NoSuchFieldException e) {
      e.printStackTrace();
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
}
```

**Additional context**

I'm also fine with doing a PR for this, if you like and accept this kind of feature.

**Comment by johnou** [comment]
@kuujo can we just expose a getter?
